global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['172.18.0.12:9100']

  - job_name: 'k6'
    static_configs:
      - targets: ['localhost:6565']

remote_write:
  - url: "http://172.18.0.3:9090/api/v1/write"
